/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jighthouse;

public class App {

    // TODO: REMOVE this class

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
